name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  format-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  
      contents: read 
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd ./mywebapp
          npm install

      - name: Build the project
        run: |
          cd ./mywebapp
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages


