name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  format-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Prettier
        run: npm install --save-dev --save-exact prettier
        
      - name: Format code with Prettier
        run: npx prettier . --write
        
      - name: Build the project
        run: npm run dev # เพิ่มขั้นตอนการ build ที่นี่ถ้าจำเป็น


      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
          publish_dir: ./mywebapp  # หรือ ./ ถ้าคุณต้องการใช้ root directory
