name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # branch ที่ต้องการให้ deploy เช่น main หรือ master

jobs:
  format-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          if [ -f package.json ]; then
            npm install
          else
            echo "No package.json found, skipping npm install."
          fi


      - name: Install Prettier
        run: npm install --save-dev --save-exact prettier

      - name: Format code with Prettier
        run: npx prettier . --write  # จัดฟอร์แมตโค้ดทั้งหมด

      - name: Check code formatting with Prettier
        run: npx prettier --check "**/*.{html,css,js}"  # ตรวจสอบฟอร์แมตโค้ด HTML, CSS และ JS

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # ระบุ root directory (ไม่ต้องมีชื่อโฟลเดอร์)
