name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main  # branch ที่ต้องการให้ deploy เช่น main หรือ master
jobs:
  format-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          publish_dir: ./mywebapp
      - name: Install dependencies
        run: npm install
      - name: Install Prettier
        run: npm install --save-dev --save-exact prettier
        
      - name: Check code formatting with Prettier
        run: npx prettier --check "**/*.{html,css,js}"  # ตรวจสอบฟอร์แมตโค้ด HTML, CSS และ JS
      - name: Format code with Prettier
        run: npx prettier . --write  # จัดฟอร์แมตโค้ดทั้งหมด
 
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./mywebapp
